<?php

namespace AppBundle\Repository;

/**
 * VoucherItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoucherItemRepository extends \Doctrine\ORM\EntityRepository
{
}
